### ISSUE TITLE
Platform Specific code in flashcart_core

### ISSUE THREAD

**Issue by kitling** [ntrteam/flashcart_core#1]
https://github.com/kitling/flashcart_core/blob/master/device.cpp#L141-L152 and https://github.com/kitling/flashcart_core/blob/23e5882a3e57257be58c910fd1205625fcd660c8/device.cpp#L39

This stuff should be in ntrboot_flasher. Due to the semi-rushed release of last night, I did not get around to moving these around.

We should also find a better API for exposing platform specific stuff.

**Comment by Juanito9001** [comment]
what does mean that the HW REV and the chip ID Appears like FFFFFFFF?
does means that the R4 is fake?? or means that doesn´t have support yet?

**Comment by kitling** [comment]
I have no clue, @Juanito9001. https://github.com/kitling/ntrboot_flasher/issues/3#issuecomment-322000616

Don't ask on an unrelated issue.

**Comment by kitling** [comment]
This has been mostly fixed, except for the usage of ioDelay.

**Comment by angelsl** [comment]
I guess we can close this now, right?
