### ISSUE TITLE
R4 SDHC Dual-Core (www.r4isdhc.com.cn)

### ISSUE THREAD

**Issue by minerplays** [ntrteam/flashcart_core#101]
I got a card off of nds-card a while back, but the question is <strike>will it blend</strike>, will it work with boothax

ChipID: FF3F0000
HW Revision: Unknown

<details><summary>Images <em>(Click to Expand)</em></summary><p> 

![img_0014](https://user-images.githubusercontent.com/30768987/32025154-0faf6cf0-b9d7-11e7-9db3-1653398b83de.jpg)

![img_0013](https://user-images.githubusercontent.com/30768987/32025169-1a74a1be-b9d7-11e7-8717-d9653c34871c.jpg)

</p></details> 

GM9 Untrimmed Dump: 
[DEEPLABYRINT_ADLEEB_00.nds.zip](https://github.com/kitling/flashcart_core/files/1416274/DEEPLABYRINT_ADLEEB_00.nds.zip)

**Comment by ShadixAced** [comment]
Planned support, so please wait.

**Comment by trbocode** [comment]
Ace3DS compatible.

**Comment by angelsl** [comment]
Closing in favour of #33
