### ISSUE TITLE
R4 SDHC DUAL CORE 2017 .COM.CN 

### ISSUE THREAD

**Issue by agen4er** [ntrteam/flashcart_core#108]
ChipID: 
HW Revision: 

<details><summary>Images <em>(Click to Expand)</em></summary><p> 

</p></details> 

GM9 Untrimmed Dump:

**Comment by angelsl** [comment]
Dupe of #101

**Comment by trbocode** [comment]
@angelsl #101 is actually a dupe of #33 . Both carts are the same, I confirmed it (My .com.cn card has an Ace3DS chipID).

**Comment by angelsl** [comment]
@trbocode

Oh right, I forgot. Thanks.
