### ISSUE TITLE
could someone upload an r41 rts sdhc backup bin? I can't use the magnet links on the 3ds,guide website

### ISSUE THREAD

**Issue by maniack11** [ntrteam/flashcart_core#113]
<details><summary>Images <em>(Click to Expand)</em></summary><p> 

</p></details> 

GM9 Untrimmed Dump:

**Comment by kitling** [comment]
[R4i-SDHC_3DS_RTS-Flashrom.zip](https://github.com/ntrteam/flashcart_core/files/1508529/R4i-SDHC_3DS_RTS-Flashrom.zip)

I think that's the one you were asking for.

(This really isn't the place though, Discord or IRC would be better for getting help w/ the guide.)

**Comment by maniack11** [comment]
thank you
