### ISSUE TITLE
R4i SDHC (ndsiLL.com) v1.4 (BLUE colour)

### ISSUE THREAD

**Issue by Bolt23** [ntrteam/flashcart_core#119]

**Comment by jason0597** [comment]
are you using the .firm flasher or the .nds flasher?

**Comment by Bolt23** [comment]
.FIRM

**Comment by Bolt23** [comment]
Can anyone compile the latest commit so that I can try once more for NTRBootHax injection.

**Comment by jason0597** [comment]
[here's the latest commit](https://www.dropbox.com/s/fz187pirzqgkj3x/ntrboot_flasher.firm?dl=0)

**Comment by Bolt23** [comment]
Can you provide a direct link, I am working on mobile and using multidownload++. Dropbox doesn’t seem to work.

**Comment by Bolt23** [comment]
Downloaded and used. Still no luck! Dual core option seems to detect it but injection fails! R4i HOLD 3DS option doesn't detect as compatible but SDHC family does but Injection fails! Restoration with any option fails too! My Flashcart has now some problem the games are glitched from the bottom (Horizontal Glitchy Line). Though this commit is 8 days old. Please @jason0597 compile the latest commit with latest flash cart core. I must do something for N2DSXL

**Comment by Bolt23** [comment]
Wait! The restoration option on Dualcore option seems to work absolutely fine! But still injection Fails! This means if restoration works then injection might work too some day.

**Comment by kitling** [comment]
Could you upload /ntrboot/ntrboot.log after trying both dualcore and r4i gold 3ds?

**Comment by dark-samus** [comment]
If it's working with TTMENU, it could possibly be a DSTT(I) clone. Try with
DSTT support.

**Comment by Bolt23** [comment]
DSTT option says that the Flashcart isn’t supported! Nor the latest commit provided above nor the original 0.3.1 Release nor the Commit compiled on Nov. 26. I’ll provide the logs ass soon as I can get FTP to work with my iPad! Thanks NTR Team

**Comment by Bolt23** [comment]
The restoration using R4 DualCore option said successfully restored but I still get a horizontal glitch line at the bottom of both the screens and games still say that the save file has been corrupted due to damage (No problem! I still have a game .sav backup)

**Comment by dark-samus** [comment]
@Bolt23 please upload the DSTT log.

**Comment by Bolt23** [comment]
[ntrbootA.log](https://github.com/ntrteam/flashcart_core/files/1574106/ntrbootA.log) R4i SDHC (Option) (Latest Commit provided above)
[ntrbootB.log](https://github.com/ntrteam/flashcart_core/files/1574108/ntrbootB.log) R4 Dual Core (Option) (Latest Commit provided above)
[ntrbootC.log](https://github.com/ntrteam/flashcart_core/files/1574110/ntrbootC.log) R4i Gold 3DS (Option) (Commit compiled on Nov. 26)

The latest release (0.3.1) did not detect it as R4i Gold 3DS nor as R4i SDHC. Neither of the three commits used by me the DSTT option always says “Your Flashcart isn’t supported”. I even tried old releases still no luck!

**Comment by Bolt23** [comment]
Should I change the NTR LOG type from info to debug or something the reupload? @kitling @dark-samus @jason0597

**Comment by dark-samus** [comment]
I was wanting a log from the DSTT option. Even if it's not supported it
still spits out a log.

**Comment by Bolt23** [comment]
[ntrbootD.log](https://github.com/ntrteam/flashcart_core/files/1574417/ntrbootD.log) DSTT log (Commit from Nov. 26)
[ntrbootE.log](https://github.com/ntrteam/flashcart_core/files/1574423/ntrbootE.log) DSTT log (Latest Commit provided above)

**Comment by dark-samus** [comment]
hmm, well, really I'd need to see the flashchip/get the numbers off of it so I could take a look at a datasheet to implement this one into the DSTT code...

**Comment by Bolt23** [comment]
Thanks a TON! I will the most happy person owning a N2DSXL with CFW only because @dark-samus  helped me! Thanks! You are a genius! Yay!

Now, I don’t know how to dump through GM9 though I have the dumped flash from ntrboot_flasher (backup.bin)

**Comment by Bolt23** [comment]
[Trimmed ROM.zip](https://github.com/ntrteam/flashcart_core/files/1574659/Trimmed.ROM.zip) Trimmed .nds dumped using GM9 from Flash Cart.
[Dumped Flash.zip](https://github.com/ntrteam/flashcart_core/files/1574662/Dumped.Flash.zip) Dumped Flash using ntrboot_flasher

The trimmed rom indiside Gamecart Option in GM9 was simply copied to my SD Card by me and the uploaded! Thanks @dark-samus for you gave me a hope! I have faith and full confidence that you will make this compatible with ntrboothax! Yay!

**Comment by Bolt23** [comment]
I’ll try to cut it open at all costs! One thing more, can you guarantee me that first you’ll implement my Flashcart code and then other requests? Please I need it somehow before Christmas!

**Comment by jason0597** [comment]
@Bolt23 What guarantee? These people do this on their own free time, if they even manage to have free time that is.

There can never be promises and guarantees, since this is dealing with flashcart specific behaviour that is unpredictable at times. 

And this can’t be done on short notice. Hundreds of other people have used this software to flash their flashcarts, and they haven’t asked for any deadline or anything like that.

**Comment by Bolt23** [comment]
@jason0597 I didnt mean that! I don’t want special treatment! I meant that will my current Flashcart will work in the future or not?

**Comment by Bolt23** [comment]
@dark-samus @kitling @jason0597

**Comment by Bolt23** [comment]
Sorry! I pressed the close button by mistake! I am a Child and make some mistakes, Sorry! I am just 12 years

**Comment by Chaos33** [comment]
Good! Team NTR help this guy apologising for his mistake and me too! Yo!

**Comment by Bolt23** [comment]
Keep up the good work team! Love your work! Big Fan now!

**Comment by Chaos33** [comment]
@Bolt23 Are you mad? You closed the issue and reopened it again at the same moment? Darn these kids!

**Comment by Bolt23** [comment]
@Chaos33 Please stick to the point we are trying to do some work here! Please for god’s sake don’t mess with the issue chat! 

@dark-samus here are the files you asked for. I am reuploading
[Untrimmed ROM.zip](https://github.com/ntrteam/flashcart_core/files/1575528/Untrimmed.ROM.zip)

**Comment by Bolt23** [comment]
@kitling @dark-samus @jason0597 Still no progress? And I have a great news too! 

Restoration from the R4i Dual Core worked flawlessly when I recopied the backup.bin from my desktop storage (Backup that I had made after dumping) i.e the backup.bin was corrupted before or the restoration didn’t work at some point before. I don’t get the glitchy lines now and DS, DSi, DSi Enhanced games, all work flawlessly without any error! Thanks to you! 

But still flashing NTRboothax still does not work from any option! But this confirms that flashing works. I cannot cut open my Flashcart and might not be able to show you the inside PCB. Still will try somehow!

**Comment by Bolt23** [comment]
@jason0597 @kitling @dark-samus I got my N2DSXL today! No support for my Flashcart? I am get too much excited!

**Comment by Bolt23** [comment]
@kitling @dark-samus @jason0597 Update: I used DSTT_Flash_Checker.nds (0.1) on my flashcart from YSMenu and it says that "This cart isn't DSTT"! this means that R4i BLUE 1.4 isnt a DSTT but maybe a R4i SDHC or R4i Dual Core, beacause the commit from above detects it as them! even the look of the flash cart looks like a R4i SDHC! I am 99% sure that it is a R4i SDHC and its 50-50 that it maybe a R4i Dual Core!

**Comment by Bolt23** [comment]
@kitling @dark-samus Any Update? Maybe I should try DSi Ware Game Injection

**Comment by kitling** [comment]
Sorry, we haven't been actively working on this cart.

FYI, the R4i Dualcore has absolutely no detection logic as of yet, so it's unlikely that this cart is one of those.

**Comment by Bolt23** [comment]
@kitling Thanks Bud! You bring tears in my eyes, for seeing an awesome developer like you caring for his creation’s user. Applause! You are the best! A developer feeling sorry for he was not able to update his code for the end user, is a true show of magnanimity! 

And for the cart? No Problem at all, take your time! Though my exams are approaching so not tension about 3DS. Thanks in advance!

**Comment by Bolt23** [comment]
@kitling I just used the DS FIRM checker from the github repository (@ntrteam) and used it. The results:

ncgc_nbegin_key1 failed:
-2 0x00000000 0x0E112A02

I don't know what the above means but it might be something useful to you. @kitling @dark-samus Thanks in Advance!

**Comment by Bolt23** [comment]
@kitling #75 The guy there gets the same error as me and restoration works for me too. @zoogie Maybe you can help me.

BTW @zoogie I am your BIG FAN cuz you provided the fasthax+safehax kernel hack with the Cart FIX which finally allowed A9LH on my N3DS. You are an awesome guy who fulfilled a child's fantasy of hacking his 3DS and playing all GAMES, HACKS and what not! Thanks! I ain't praising you for you to fix my FLASHCART problem. No Way! Just cuz I never got to thank you on any forum. I am justifying cause @jason0597 might find me false praising you for some sort of advantage. Keep Up the Good Work!

@kitling What to do with this flashcart? It gets the same error that R4i GOLD does in #75 and for me DUMPING WORKS from all options but RESTORATION only works from R4i Dual Core option in the commit provided above in comment 3 or 4

**Comment by Bolt23** [comment]
Maybe I can restore a NTRBOOTHAXED backup.bin as injection doesn't work? @dark-samus What do you say?

**Comment by Bolt23** [comment]
Happy One-Month Anniversary  to my issue #119 @kitling @dark-samus @zoogie @angelsl @jason0597 Thanks for your support!

**Comment by Bolt23** [comment]
@kitling @dark-samus @zoogie I finally managed to compile it
[ntrboot_flasherAR.zip](https://github.com/ntrteam/flashcart_core/files/1659709/ntrboot_flasherAR.zip)
 myself and still injection failed!

**Comment by Bolt23** [comment]
@kitling @dark-samus @zoogie  I get a norErase4k error... This was also found in prior commits that I used the NOR Flash something kind of error...... 
[ntrboot_log.zip](https://github.com/ntrteam/flashcart_core/files/1659776/ntrboot_log.zip) What to do?Please help me!

**Comment by Bolt23** [comment]
No Update! No issue!

**Comment by kitling** [comment]
Just because nobody has been actively working on the cart doesn't mean the cart doesn't exist. Reopening.

**Comment by Bolt23** [comment]
I already hacked my N2DSXL 18 months ago using DSi Ware had and 2 bucks on DSi game. Thanks for all above works, data and implementation! Cheers.

**Comment by kitlith** [comment]
*Just because you don't need it anymore doesn't mean it doesn't exist*. Reopening.

(though I guess this is more out of principle more than anything else, seeing as I'm not really working on this.)
