### ISSUE TITLE
r4ids.cn rev5

### ISSUE THREAD

**Issue by zoogie** [ntrteam/flashcart_core#21]
This is a strange issue since it's resolved on my end. I have a *really* old r4iGold (rev5) that I managed to get working with ntrboot. 
It's looks like the card on the top row, far right:
http://www.r4wood.com/pages/R4i-Gold.html

Anyway, I haven't seen a single other person with this card so I don't think it's worth a pull request, but some people might want to look at the script if they have the card.
Here's the gist of it:
https://gist.github.com/zoogie/51856a507bf380fc38d82a87855e265f
It's pretty simple and straightforward so no further explanation needed I think.

**Comment by dark-samus** [comment]
@zoogie could I get a picture of the PCB of this card? Please and thanks :)

**Comment by zoogie** [comment]
@dark-samus here you go.
Also included the bootloader and ROM image dumps. The images are clean of hacks.
[r4ids_rev5.cn.zip](https://github.com/kitling/flashcart_core/files/1250913/r4ids_rev5.cn.zip)

![2017-08-24 23 50 19](https://user-images.githubusercontent.com/28328903/29700638-174d9846-892c-11e7-9ab7-21f66c94b9c5.jpg)

The cart shows up as chipID 0xFC2 an rev 0x00000000 in ntrboot flasher.

**Comment by dark-samus** [comment]
oh, excellent, looks like this is actually sort of a duplicate issue. I'll see about figuring out how to integrate the results into ntrboot_flasher... is there a way the crypto can be expressed more like how it is for the original cart? Or is it different than that? (I can't read python too well, heh) Is there any way I could get a C representation of the encryption you've got going there?

**Comment by zoogie** [comment]
Yeah, this is quite similar to @Banamy 's issue. He has a rev6. I've been trying to help him to get that to work but no luck.

Anyway, back to this issue, the C code for the crypto would look something like this:
u8 r4iflash[0x200000];
u32 b9s_payload_offset=0x82200;
u8 b9s_payload[b9s_payload_len];
u8 xorpad_byte=0;

for(u32 i=0; i < b9s_payload_len; i++) {
	xorpad_byte = b9s_payload_offset % 256 + 9;
	r4iflash[b9s_payload_offset + i] = xorpad_byte ^ b9s_payload[i];
}

**Comment by tarek996** [comment]
Hey I have the same card as you could you please tell me how you got it working? Like the steps etc... thank you!

**Comment by zoogie** [comment]
@tarek996 sure! If you want to be the first tester, just run this:
http://s000.tinyupload.com/index.php?file_id=36989795732834494913
and "Dump Flash". Upload here what's dumped in sdmc:/ntrboot/backup.bin.

Need to verify a couple of things before you try a test image.

**Comment by Xeon3D** [comment]
@zoogie I have a Rev. 4 from r4ids.com. Did you get your version to run ntrboot? If so, can you explain how can I try on mine? The carts look pretty much identical.

Also, what game does it show as on the 3ds?

**Comment by zoogie** [comment]
@Xeon3D Go ahead and PM me on Gbatemp and I'd be glad to help you.

**Comment by toby1911** [comment]
@zoogie I also got Rev.4 (clone) . I get the same files and sizes when i make a Dump. And would be also interessted for the Rev 4 version :)

**Comment by Leadger69** [comment]
I just tried this dump aswell and got the same chip ID 00000FC2 and HW Rev 00000000
and my cart is rev7

**Comment by Xeon3D** [comment]
@zoogie's script made mine work. My Rev. 4 cart with r4ids.com on the label is now able to run safeb9sinstaller :)

**Comment by zoogie** [comment]
Great news Xeon3D! 

@toby1911 
Download this:
http://s000.tinyupload.com/index.php?file_id=00664373029281777476
Get your dumped backup.bin with this app.  (keep this for safekeeping and don't lose it)

Then get boot9strap_ntr.firm from here
https://github.com/al3x10m/boot9strap/files/1294179/1.3.load.ntrboot.firm.zip

Get blowfish_retail.bin from here
https://github.com/kitling/ntrboot_flasher/blob/master/data/blowfish_retail.bin

Put all those 3 files in the same directory with my script (first post in this issue) then run the script. Rename the resulting backup_patched.bin to backup.bin then place it in sdmc://ntrboot/backup.bin then restore it.

**Comment by Leadger69** [comment]
Would this work for mine or no?

**Comment by zoogie** [comment]
@Leadger69 - I think not. @Banamy 's rev6 had different crypto and offsets so yours likely will too. Also, I recommend you make a new issue for the rev7, and follow the guidelines for requesting new card support.
https://github.com/kitling/flashcart_core#requesting-support-for-a-new-cart

**Comment by kitling** [comment]
@zoogie Could we work together to get your reading/writing code into flashcart_core (if it's different from known r4i gold 3ds stuff)? I'm available in #Cakey on IRC and in the Nintendo Homebrew discord as Kitlith for live collaboration on this.

**Comment by toby1911** [comment]
@zoogie Thanks it worked very well without any issues. I was also able to flash my backup back. :)

**Comment by kitling** [comment]
Belatedly closing this since support has been added to the flasher.

**Comment by zoogie** [comment]
Everyone, could you please do me a favor? We need some info to help support more versions of the r4iGold. This is all you have to do:

After downloading this https://github.com/ntrteam/flashcart_core/files/1472600/ntrboot_flasher.zip
Please insert your rev4-5, boot the app, press Y until you see "Log Level: DEBUG" in the bottom right of the top screen. Then "Dump Flash". The backup.bin dump isn't important, look at ntrboot.log in sdmc://ntrboot/ and tell us what number is after "[NOTICE]: R4iGold: HW C7 value = ". Also let us know what r4igold revision you have. Back of card over the right connector pin.

**Comment by Xiiflowx** [comment]
@zoogie 
I've got 3 rev4 clones from r4ids.com, it seems that it stays the same.
1 - [NOTICE]: R4iGold: HW C7 value = a79bca95    (R4I DS V1.4 written on back)
2 - [NOTICE]: R4iGold: HW C7 value = a79bca95    (R4I DS V1.4 written on back)
3 - [NOTICE]: R4iGold: HW C7 value = a79bca95    (4 written on back)

**Comment by zoogie** [comment]
@zoogie
That's what our assumption was. Glad to see it mostly confirmed. Thanks!
