### ISSUE TITLE
NEW R4i (r4i-sdhc.hk)

### ISSUE THREAD

**Issue by hectortillo** [ntrteam/flashcart_core#34]
I have a rare R4i Revolution "NEW" clone, it doesnt load the kernel from the site it has printed on the front (but it works with the kernel from the Blue gateway card) and the board is very different from the ones that has been posted, but also the picture is basically the same (but in black) 
it loads with this kernel ([link](https://mega.nz/#!pGZGhBra!--eXezyWaDHgrnhEGSVIMgBkam1BkC5BlbBqrf7apkM))
and i dont have any firmware updater as i dont know a page that could work the kernel with this clone. 

  <details><summary>Images <em>(Click to Expand)</em></summary><p> 

![Front + PCB Front](https://user-images.githubusercontent.com/6589032/29715596-a5ae47de-896d-11e7-8dba-9838536658c0.jpg)
![PCB Front](https://user-images.githubusercontent.com/6589032/29715606-b5be0966-896d-11e7-9458-0e47e4d2a276.jpg)
![PCB Back](https://user-images.githubusercontent.com/6589032/29715614-bd27da92-896d-11e7-811d-d471ec2be3e8.jpg)

  </p></details> 

GM9 dump of cart: https://mega.nz/#!5OhBlTSL!ErXsQFuh57_unRp8Xjrts6Ea_rH29UtN8tL8Sjop5Rg

**Comment by dark-samus** [comment]
please, follow the instructions [in the README](https://github.com/kitling/flashcart_core#requesting-support-for-a-new-card)

**Comment by kitling** [comment]
@dark-samus they're one of the first using the new issue template, click on the images arrow to see the images. (I did that to avoid image clutter all over the issue thread)

Still not sure why links afterwards don't seem to want to link. I'll have to figure that out and change the template.

**Comment by dark-samus** [comment]
OHHHHHHHHH

**Comment by hectortillo** [comment]
i purchased it from a local seller, for local i mean a "tianguis" im from mexico, it was 2nd hand purchased and then i have buyed it, i dont know where it come from :'v     also sorry @dark-samus  i dont know what i need to add :( i have read the readme but i dont know any other thing to add :(

**Comment by dark-samus** [comment]
@hectortillo I apologize. It was me not seeing that the images were actually in the little drop down.

**Comment by ShadixAced** [comment]
PCB is different from other carts, might be a different way of accessing read/write on flash.

**Comment by togglechannelelsewhere** [comment]
Hi,
I also own this cart. I got it at a flea market a few years ago. With the help of a guy on Discord, I was able to get the original kernel. @joo456 mirrored it here: https://github.com/joo456/flashcarts/raw/master/Kernels/R4i-New/WWW.R4I-SDHC.HK%20R4i%20NEW.zip
Other information that I don't think has been said yet:
- shows up as "Deep Labyrinth" by Atlas USA, Inc.
- Works on stock 3DS 11.3
- help information shows "wood akmenu 1.56 HW: 00 Sys. NDSi 1.4.5 &

**Comment by hectortillo** [comment]
Already it works on all versions of all co soles on every firmware version i tested is a jewel for that. But doesnt have RTS:'v.

**Comment by togglechannelelsewhere** [comment]
yeah, you're confusing the R4i New with r4i-sdhc.hk's other products. This particular one just uses akwood

**Comment by hectortillo** [comment]
The new 0.4.0 ntrboot flasher lets to read the flash and made a flash backup correctly, i should try if it seems to work installing NTRBoot, but i have fear to brick my r4 xd

**Comment by hectortillo** [comment]
i have done NTRBoot correctly and restored it, al works correctly and excellent, i think it doesnt need more test, many thanks

**Comment by kitling** [comment]
Glad to hear it!

**Comment by joo456** [comment]
thanks for credits :eyes:
