### ISSUE TITLE
R4 Revolution for DS (fakely rebranded as R4i-SDHC) (site unknown)

### ISSUE THREAD

**Issue by LaneSh4d0w** [ntrteam/flashcart_core#41]
This card is a hell of a fake card. The card is "bricked", and freezes every 3DS when this card is put on.
Last minute edit : It was said to be not working since a pink DS that I've had tried to make it work without success. Methinks it was an upgrade problem. At digging in my memories, it either had a timebomb or told the user when they had a "fake" firmware.
ChipID: 04040404
HW Revision: 04040404
Firmware that worked on this card before : http://www.r4i-sdhc.com/R4i%20V1.12d%20French.zip
<details><summary>Images <em>(Click to Expand)</em></summary><p> 

![img_20170829_152131](https://user-images.githubusercontent.com/30985701/29823332-a04cdb2a-8cce-11e7-8dd3-13d1426b3561.jpg)
![img_20170829_152139](https://user-images.githubusercontent.com/30985701/29823334-a19a3176-8cce-11e7-9505-4f3e42807c3e.jpg)

</p></details> 

GM9 Untrimmed Dump: not possible to have, 0 bytes on the card (as GM9 says)

Debug.log ; https://hastebin.com/cedudejuqa.md

**Comment by ShadixAced** [comment]
Tried to take a firm dump via D9, it says product name : **********
Product ID: *****
Cartridge ID : 08080800
Cartridge data size : 32mb
Cartridge used size : 128mb
Cartridge dump size : 32mb
Used size exceeds cartridge size.

**Comment by Nuck-TH** [comment]
Without pictures of cart circuit board it is hard to tell anything.

**Comment by ShadixAced** [comment]
Well when I can open the card I'm gonna put photos of the PCB.

**Comment by hedgeberg** [comment]
Yeah there's like 0% chance of this getting supported if it exhibits the behavior youve described. That being said pcb pics and purchase locations may be really helpful so we can dissuade other users from buying from there.

**Comment by ShadixAced** [comment]
Ummm... By digging into my head.. I do only remember that the card was sent from China... Not sure about the purchase site, since it has been 8 or 9 years that this card was bought.

**Comment by ShadixAced** [comment]
By the bottom, i should say that it looks like #42 but mine is revision "7".

**Comment by ShadixAced** [comment]
Finally got to the PCB, pictures are coming.

**Comment by ShadixAced** [comment]
![img_20170901_193149](https://user-images.githubusercontent.com/30985701/29981086-b2204956-8f4c-11e7-8341-98993b9106dd.jpg)
![img_20170901_193141](https://user-images.githubusercontent.com/30985701/29981090-b3ef9f8e-8f4c-11e7-9b73-157196f22771.jpg)

**Comment by ShadixAced** [comment]
@kitling Shouldn't be added as "support request" since this cart is, like @hedgeberg said, not good to use at all since it doesn't work anymore.

**Comment by ShadixAced** [comment]
Have tried with 0.3.1, cart is detected by ntrboot_flasher (which is pretty good in fact) and it is not supported by all of the methods.

**Comment by kitling** [comment]
"Not supported by all of the methods." What do you mean by that?

**Comment by ShadixAced** [comment]
I've tried all of the methods available, from AceKard to R4i Gold, i meant.

**Comment by ShadixAced** [comment]
Oh, and I have mainly tried the R4i-SDHC variant, due to the fact you've made it through ! (awesome work)

**Comment by kitling** [comment]
Okay. I hear there's a PR that may fix support for some of the older r4i-sdhc carts, I'll have you try it once it's merged and a new release is made.

**Comment by ShadixAced** [comment]
Okay, thank you @kitling ! Hope it can make mine work !

**Comment by ShadixAced** [comment]
I have another question, though the card *might* work when flashed with ntrboot_flasher, can I revert these changes and inject a R4i-SDHC kernel on it ? Would be nice !

**Comment by ShadixAced** [comment]
Also, due to the changes you've made, shouldn't it be good to precise in the readme that R4i-SDHC RTS + r4isdhc.com cards are supported, or are you making sure that a lot more of cards are supported due to the Pull Request you talked about ?

**Comment by kitling** [comment]
Oh. Right. Readme. That *does* need to be touched at some point.

As for reverting the changes, you should be able to take a backup and restore it.

**Comment by ShadixAced** [comment]
I would like to, but when it have 0 bytes even with GM9 looking at the
cart, it is completely flushed

**Comment by kitling** [comment]
I mean, you could restore with someone else's backup.

**Comment by ShadixAced** [comment]
Oh yes, just need to find who has got the same card as mine !

**Comment by ShadixAced** [comment]
@d3m3vilurr did an amazing job on the R4i cards ! Just saw the pull request, and the code he changed. He "uniformized" the NTRboot code, here i'm talking about the last part of the "gold" code, on the injectntrboottype1 and type2.

**Comment by ShadixAced** [comment]
Last minute edit : It was said to be not working since a pink DS that I've had tried to make it work without success. Methinks it was an upgrade problem. At digging in my memories, it either had a timebomb or told the user when they had a "fake" firmware.

**Comment by ShadixAced** [comment]
Ah, my ID didn't change, but my product name and ID showed something.

Name : STSTSTSTSTST
Product ID : STSTST

**Comment by kitling** [comment]
FYI 90% of carts seem to have FC2 for the chipid.

**Comment by ShadixAced** [comment]
@kitling So it means that my card is... like any other card. Something is going wrong on it so.

**Comment by ShadixAced** [comment]
At least my card is now readable as I've saw. Do I need to attach a log ? @kitling
