### ISSUE TITLE
R4 SDHC 3DS DSI www.r4isdhc.com

### ISSUE THREAD

**Issue by Legarad** [ntrteam/flashcart_core#90]
ChipID: 
HW Revision: 

I think that this can not be modified. Because it does not have the black circle on its chip

<details><summary>Images <em>(Click to Expand)</em></summary><p> 

<img src=https://user-images.githubusercontent.com/28263644/31696782-a1956180-b381-11e7-84bb-6d2354c53d27.jpg></img>
<img src=https://user-images.githubusercontent.com/28263644/31696876-23dba7a8-b382-11e7-9143-f4173216156c.jpg></img>
<img src=https://user-images.githubusercontent.com/28263644/31696877-24198b40-b382-11e7-8fb6-41fb32c37d3c.jpg></Img>

</p></details> 

GM9 Untrimmed Dump: https://github.com/kitling/flashcart_core/files/1393168/dump.zip

**Comment by benji200** [comment]
I hace this card and dont work with ntrboot :c

**Comment by Nuck-TH** [comment]
Same cart as in #3 
Refer there for information why it is not supported yet.

**Comment by ShadixAced** [comment]
@Nuck-TH Do not know where you had that info, but it's a R4 SDHC Dualcore he is talking about.

The one which is in planned support.

**Comment by kitling** [comment]
@Legarad that makes no difference as to whether it can be flashed or not.

I suspect that it's an older version of the cart just recently supported.

**Comment by Legarad** [comment]
@kitling R4iSDHC family and R4i Gold 3DS. Your Flashcart is not supported.

**Comment by Legarad** [comment]
[Firmware y Kernel.zip](https://github.com/kitling/flashcart_core/files/1405763/Firmware.y.Kernel.zip)

**Comment by dark-samus** [comment]
duplicate of #3 
closing.
