### ISSUE TITLE
R4 SDHC RTS LITE 2014 (r4isdhc.com)

### ISSUE THREAD

**Issue by I2000C** [ntrteam/flashcart_core#91]
http://www.r4isdhc.com/2014-r4isdhc-rts-lite/

The ntrflashtool freezes at 99% when I try to restore the original flash. I don't know what is the error. Please help me.

ChipID: 001F0000
HW Revision: 

<details><summary>Images <em>(Click to Expand)</em></summary><p> 

http://www.r4isdhc.com/r4-product#a1

https://drive.google.com/file/d/0BzMCjSnf32PObVc0VzVKZ1dySG8/view?usp=drivesdk

</p></details> 

GM9 Untrimmed Dump: https://drive.google.com/file/d/0BzMCjSnf32POcE16UnI3aktqalU/view?usp=drivesdk

**Comment by Legarad** [comment]
The images that they request are from the chip of the flashcart

**Comment by angelsl** [comment]
That is a strange chip ID.

Please post the log (`ntrboot/ntrboot.log`).

**Comment by I2000C** [comment]
[ntrboot.log](https://github.com/kitling/flashcart_core/files/1398884/ntrboot.log)

**Comment by I2000C** [comment]
https://web.archive.org/web/20170613162023/http://www.r4isdhc.com/wp-content/themes/nds9/images/s/3.jpg
https://web.archive.org/web/20170613162023/http://www.r4isdhc.com/wp-content/themes/nds9/images/s/4.jpg
https://web.archive.org/web/20170613162023/http://www.r4isdhc.com/wp-content/themes/nds9/images/s/5.jpg
https://web.archive.org/web/20170613162023/http://www.r4isdhc.com/wp-content/themes/nds9/images/s/6.jpg

**Comment by angelsl** [comment]
Err.

Change the log level to DEBUG, then try the R4isdhc option and post the log again.

**Comment by I2000C** [comment]
How do I do it? I don't know how to change the log level...

**Comment by angelsl** [comment]
@I2000C

Press Y at the flashcart selection menu.

There is an indicator at the bottom right.

**Comment by I2000C** [comment]
Ok, I will try it now

**Comment by I2000C** [comment]
https://drive.google.com/file/d/0BzMCjSnf32POQ01KcjhoRU5RVTg/view?resourcekey=0-jsPnvlXMHw_qnzJG4CPq9g

**Comment by I2000C** [comment]
here is the log file generated in DEBUG mode

**Comment by I2000C** [comment]
Any idea what might be causing this error?

**Comment by ShadixAced** [comment]
Some parts of your card returns 0 or FFFFFFF at NOR interrogation.

Seems weird.

**Comment by I2000C** [comment]
what do you mean with weird

**Comment by ShadixAced** [comment]
For me it should have only said other results than 0 or a bunch of F.

**Comment by I2000C** [comment]
I think maybe the tool can read the cartridge but can not write about it. But, I don't know.

**Comment by I2000C** [comment]
Then, there will be any way to solve this problem? Remember that the the ntr flasher CAN READ the cartridge

**Comment by I2000C** [comment]
Right now I just discovered why the cartridge was not restored. It turns out that I had not pressed the option to inject NTRBOOT.
